### Valid Request
POST http://localhost:8080/item
Content-Type: application/json

{
  "name": "this is a name",
  "description": "this is a description"
}

### Invalid Body Data
POST http://localhost:8080/item
Content-Type: application/json

{
  "nameTypo": "this is a name",
  "description": "this is a description"
}