
### Add Test Item
POST http://localhost:8080/item
Content-Type: application/json

{
  "name": "test name",
  "description": "test description"
}

### Update Item Success
DELETE http://localhost:8080/item/26554
Content-Type: application/json

### Verification
GET http://localhost:8080/item/26554
Accept: application/json

